myshop/urls.py
import django.urls
from django.views.generic import TemplateView

import myshop.views as myshop
app_name = 'myshop'

urlpatterns = [
    django.urls.path('', myshop.index, name='index'),
    django.urls.path('products/', myshop.product_list, name='product_list'),
    # django.urls.path('products/',
    #                  myshop.ProductsListView.as_view(),
    #                  name='product_list'),
    django.urls.path('products/create/',
                     myshop.ProductKindCreateView.as_view(),
                     name='product_create'),
    django.urls.path('about/', TemplateView.as_view(template_name='myshop/about.html'), name='about'),

]

shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop.settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('', include('myshop.urls', namespace='myshop')),
    path('shopauth/', include('shopauth.urls', namespace='shopauth')),
    path('admin/', admin.site.urls),
]

if DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shopauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import shopauth.views as shopauth

app_name = 'shopauth'

urlpatterns = [
    path('user/create/',
         shopauth.ShopUserCreateView.as_view(),
         name='user_create'),
    path('login/',
         LoginView.as_view(),
         name='login'),
    path('logout/',
         LogoutView.as_view(),
         name='logout'),
    # path('logout/', shopauth, name='logout'),

]

myshop/models.py
from django.db import models


class ProductKind(models.Model):
    name = models.CharField(max_length=128, db_index=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Вид продукта'
        verbose_name_plural = 'Виды продуктов'
        ordering = ['name']


class Product(models.Model):
    name = models.CharField(max_length=32, unique=True)
    # image = models.ImageField(upload_to='product', blank=True, null=True)
    kind = models.ForeignKey(ProductKind, on_delete=models.CASCADE, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукты'
        verbose_name_plural = 'Продукты'
        ordering = ['pk']


# class Kind(models.Model):
#     name = models.CharField(max_length=32, unique=True)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     image = models.ImageField(upload_to='kind')
#
#     def __str__(self):
#         return self.name
#
#
# class Weight(models.Model):
#     name = models.IntegerField()
#     kind = models.ForeignKey(Kind, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.name
#
#
# class Price(models.Model):
#     name = models.IntegerField(unique=False)
#     weight = models.OneToOneField(Weight, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.name
#
#
# class Card(models.Model):
#     name = models.CharField(max_length=64, blank=True, unique=False)
#     kind = models.ForeignKey(Kind, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.name

shopauth/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User, AbstractUser
from django.db import models


# class ShopUserProfile(models.Model):
#     user = models.OneToOneField(User,
#                                 primary_key=True,
#                                 on_delete=models.CASCADE)
#     avatar = models.ImageField(blank=True)
#     d_birth = models.DateField(blank=True, null=True)
#     bio = models.TextField(blank=True)


class ShopUser(AbstractUser):
    email = models.EmailField('email address', unique=True)
    d_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(blank=True)

shopauth/forms.py
from django.contrib.auth.forms import UserCreationForm

from shopauth.models import ShopUser


class ShopUserCreateForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field_obj in self.fields.items():
            field_obj.help_text = ''
            # field_obj.widget.attrs['class'] = 'form-control'
            # print(field_name, field_obj.help_text)

myshop/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from myshop.models import Product, ProductKind


def index(request):
    return render(request, 'myshop/index.html')


def product_list(request):
    products = Product.objects.all()
    context = {
        'p_title': 'Shop of products',
        'product_list': products
    }
    return render(request, 'myshop/product_list.html', context=context)


# class ProductsListView(ListView):
#     model = Product
#

    # template_name = 'myshop/product_list.html'
    # context_object_name = 'product_list'
    # paginate_by = 5


# def about(request):
#     return render(request, 'myshop/about.html')


class ProductKindCreateView(CreateView):
    model = ProductKind
    success_url = reverse_lazy('myshop:product_list')
    fields = ('name',)

shopauth/views.py
from django.views.generic import CreateView


from shopauth.forms import ShopUserCreateForm
from shopauth.models import ShopUser


class ShopUserCreateView(CreateView):
    model = ShopUser
    success_url = '/'
    form_class = ShopUserCreateForm
    # fields = ('username', 'password1', 'password2')

myshop/templates/myshop/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Shop</title>
</head>
<body>
<h1>Best Shop</h1>
<a href="{% url 'myshop:index' %}">Main</a>
</body>
</html>

myshop/templates/myshop/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
</head>
<body>
<h1> Hi </h1>
<ul>
    <li>
        <a href="/">Main</a>
    </li>
    <li>
        <a href="/products/">Products</a>
    </li>
    <li>
        <a href="{% url 'myshop:about' %}">About</a>
    </li>
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'shopauth:logout' %}">
                Logout ({{ user.username }})
            </a>
        {% else %}
            <a href="{% url 'shopauth:login' %}">
                Login
            </a>
        {% endif %}
    </li>
</ul>

</body>
</html>

myshop/templates/myshop/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ p_title|default:"Shop" }}</title>
</head>
<body>
<h1> Welcome </h1>
<ul>
    <li>
        <a href="/">Main</a>
    </li>
    <li>
        <a href="/products/">Products</a>
    </li>
</ul>
    <a href="{% url 'myshop:product_create' %}">New ProductKind</a>

<div class="products-list">
    <ul>
        {% for item in object_list%}
            <li>
                {{ item }}
            </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

myshop/templates/myshop/productkind_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
</head>
<body>

<a href="{% url 'myshop:index' %}">Main</a>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save">
</form>

</body>
</html>

shopauth/templates/shopauth/shopuser_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<div class="user-creation-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
</div>
</body>
</html>